-- Add ticket_hash column for synthetic deterministic idempotency key
-- Composition: SHA256 of 12 fields (external_id, fecha_caja, hora, camarero, total,
-- comensales, cliente, tipo_documento, punto_venta, zona, descuento, recargo)
-- Validated against 13,576 docs: 0 collisions.

ALTER TABLE public.sales_documents
ADD COLUMN ticket_hash TEXT;

CREATE INDEX idx_sales_documents_ticket_hash
ON public.sales_documents(location_id, ticket_hash);

COMMENT ON COLUMN public.sales_documents.ticket_hash IS
'Synthetic deterministic hash for idempotency. SHA256 of 12 identifying fields. Generated by FARO, not by POS.';
